export const FETCH_CAR_MODELS = 'FETCH_CAR_MODELS';
export const SAVE_CAR_MODELS = 'SAVE_CAR_MODELS';
export const SAVE_USER_RESERVATION_FEED = 'SAVE_USER_RESERVATION_FEED';
export const UPDATE_USER_RESERVATION_FEED = 'UPDATE_USER_RESERVATION_FEED';
export const REMOVE_USER_RESERVATION_FEED = 'REMOVE_USER_RESERVATION_FEED';